BIN_DIR = bin
SRC_DIR = src
INCLUDE_DIR = include

sorting:
	g++ -o $(BIN_DIR)/sorting $(SRC_DIR)/sorting.cpp -I $(INCLUDE_DIR)
	./$(BIN_DIR)/sorting

operations:
	g++ -o $(BIN_DIR)/operations $(SRC_DIR)/operations.cpp -I $(INCLUDE_DIR)
	./$(BIN_DIR)/operations

search:
	g++ -o $(BIN_DIR)/search $(SRC_DIR)/search.cpp -I $(INCLUDE_DIR)
	./$(BIN_DIR)/search


clean:
	rm -rf $(BIN_DIR)/*